. "$HOME/.bashrc"

XDG_CURRENT_DESKTOP="sway"
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"

EDITOR="nvim"
GNUPGHOME="$XDG_DATA_HOME/gnupg"
GOPATH="$XDG_DATA_HOME/go"
BUN_INSTALL="$XDG_DATA_HOME/bun"
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
ANDROID_USER_HOME="$XDG_DATA_HOME/android"
ANDROID_HOME="$XDG_DATA_HOME/android/sdk"
GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"

HISTFILE="$XDG_STATE_HOME/bash/history"
LESSHISTFILE="$XDG_STATE_HOME/less/history"
MYSQL_HISTFILE="$XDG_STATE_HOME/sql/mysql_history"
PSQL_HISTORY="$XDG_STATE_HOME/sql/psql_history"
PATH="$PATH:$HOME/.local/bin:$GOPATH/bin:$XDG_DATA_HOME/npm/bin:$BUN_INSTALL/bin"

export XDG_CURRENT_DESKTOP XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME \
    XDG_STATE_HOME EDITOR GNUPGHOME GOPATH BUN_INSTALL NPM_CONFIG_USERCONFIG \
    ANDROID_USER_HOME ANDROID_HOME GRADLE_USER_HOME HISTFILE LESSHISTFILE \
    MYSQL_HISTFILE PSQL_HISTORY PATH

[ "$(tty)" = "/dev/tty1" ] && exec sway
